<div class="slide-text-content">
    <div class="container-fluid">
        <div id="content-header-slide" class="owl-carousel">
            <?php if(!empty($items)): ?>

                <?php /* @var $item \CmsIr\Slider\Model\SliderItem */?>
                <?php foreach($items as $item): ?>

                    <div class="item">
                        <img src="<?php echo $this->basePath('files/slider/' . $item->getFilename()); ?>" class="img-responsive" alt="image"/>
                    </div>
                    
                <?php endforeach ?>

            <?php else: ?>

                <div class="item">
                    <h1>BOOTSTRAP TEMPLATE SPECIALIST</h1>
                    <div class="clear"></div>
                    <h3>
                        Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet<br />
                        doming id quod mazim placerat facer possim assum.
                    </h3>
                    <div class="clear"></div>
                    <button class="btn btn-lg btn-warning btn-learn-more btn-border-only">LEARN MORE</button>
                    <a href="#" target="_blank" class="btn btn-lg btn-success btn-learn-more">PURCHASE NOW</a>
                </div>
                <div class="item">
                    <h1>ALL TEMPLATE CRAFTED WITH LOVE</h1>
                    <div class="clear"></div>
                    <h3>
                        Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet<br />
                        doming id quod mazim placerat facer possim assum.
                    </h3>
                    <div class="clear"></div>
                    <button class="btn btn-lg btn-warning btn-learn-more btn-border-only">SEE OUR WORK</button>
                </div>
                <div class="item">
                    <h1>HIGH QUALITY AND PREMIUM TEMPLATE</h1>
                    <div class="clear"></div>
                    <h3>
                        Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet<br />
                        doming id quod mazim placerat facer possim assum.
                    </h3>
                    <div class="clear"></div>
                    <a href="#" target="_blank" class="btn btn-lg btn-success btn-learn-more">PURCHASE NOW</a>
                </div><!-- /.item -->

            <?php endif ?>
        </div><!-- /.#content-header-slide -->
    </div><!-- /.container -->
</div><!-- /.slide-text-content -->