<div class="col-sm-6 col-md-3">
    <h4>SIGN UP NEWSLETTER</h4>
    <p>
        Laritas est etiam processus dynamicus, qui
        sequitur mutationem consuetudium
        lectorum. Mirum est notare quam littera.
    </p>
    <form role="form">
        <div class="input-group subscribe">
            <input type="text" class="form-control" placeholder="Enter email address">
							  <span class="input-group-btn">
								<button class="btn btn-info" type="button"><i class="fa fa-chevron-right"></i></button>
							  </span>
        </div><!-- /input-group -->
    </form>
</div><!-- /.col-sm-3 -->