<!-- Begin nav menu -->
<ul class="menus">
    <li class="parent">
        <a href="#fakelink">Home</a>
        <ul class="sub-menus">
            <li class="sub-list"><a href="#">Default</a></li>

            <li class="sub-list"><a href="#">Fancy color navbar <span class="label label-danger">HOT</span></a></li>
            <li class="sub-list"><a href="#">Static nav position</a></li>
            <li class="sub-list">
                <a href="#fakelink">Dark nav color <span class="badge badge-success">3</span></a>
                <ul class="subsub-menus">
                    <li class="subsub-list"><a href="#">Static image header</a></li>
                    <li class="subsub-list"><a href="#">Image slide</a></li>
                    <li class="subsub-list"><a href="#">Content slide</a></li>
                </ul>
            </li>
            <li class="sub-list">
                <a href="#fakelink">Light nav color <span class="badge badge-warning">3</span></a>
                <ul class="subsub-menus">
                    <li class="subsub-list"><a href="#">Static image header</a></li>
                    <li class="subsub-list"><a href="#">Image slide</a></li>
                    <li class="subsub-list"><a href="#">Content slide</a></li>
                </ul>
            </li>
            <li class="sub-list">
                <a href="#fakelink">Transparent nav <span class="badge badge-info">3</span></a>
                <ul class="subsub-menus">
                    <li class="subsub-list"><a href="#">Static image header</a></li>
                    <li class="subsub-list"><a href="#">Image slide <span class="label label-primary">DEFAULT</span></a></li>
                    <li class="subsub-list"><a href="#">Content slide</a></li>
                </ul>
            </li>

            <li class="sub-list"><a href="#">Background color</a></li>
            <li class="sub-list">
                <a href="#fakelink">Templates <span class="label label-primary">PACKAGE</span></a>
                <ul class="subsub-menus">
                    <li class="subsub-list"><a href="#" target="_blank">Sentir - Admin template</a></li>
                    <li class="subsub-list"><a href="#">Sentir - One page</a></li>
                    <li class="subsub-list"><a href="#">Sentir - Coming soon</a></li>
                </ul>
            </li>
        </ul>
    </li>
    <li class="parent">
        <a href="#fakelink">Pages</a>
        <ul class="sub-menus">
            <li class="sub-list"><a href="#">About us</a></li>
            <li class="sub-list"><a href="#">Full width</a></li>
            <li class="sub-list"><a href="#">Sidebar left</a></li>
            <li class="sub-list"><a href="#">Sidebar right</a></li>
            <li class="sub-list"><a href="#">Services</a></li>
            <li class="sub-list"><a href="#">Testimonial</a></li>
            <li class="sub-list"><a href="#">Pricing table</a></li>
            <li class="sub-list"><a href="#">Blank page</a></li>
        </ul>
    </li>
    <li class="parent">
        <a href="#">Shortcodes</a>
    </li>
    <li class="parent">
        <a href="#fakelink">Portfolio</a>
        <ul class="sub-menus">
            <li class="sub-list"><a href="#">4 columns</a></li>
            <li class="sub-list"><a href="#">3 columns</a></li>
            <li class="sub-list"><a href="#">Portfolio single</a></li>
        </ul>
    </li>
    <li class="parent">
        <a href="#fakelink">Blog</a>
        <ul class="sub-menus">
            <li class="sub-list"><a href="#">Blog list</a></li>
            <li class="sub-list"><a href="#">Blog detail</a></li>
        </ul>
    </li>
    <li class="parent"><a href="#">Contact</a></li>

    <!-- Begin right icon -->
    <li class="parent right-icon">
        <i class="fa fa-search" id="nav-icon-search"></i>
    </li>
    <li class="parent right-icon">
        <i class="fa fa-phone" id="nav-icon-phone"></i>
    </li>
    <!-- End right icon -->
</ul>
<!-- End nav menu -->